apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: wog
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  # The selector tells the service on which deployment it should be applied
  selector:
    app: wog