# Wishlist deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: api  
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: yahel777/wog-api:v2
        ports:
        - containerPort: 5001
        # env:
        # - name: PORT
        #   value: "5001"
        # - name: DB_HOST
        #   value: db
      # - name: auth #3rd container
      #   image: karthequian/wishlist-auth:1.0
      #   ports:
      #   - containerPort: 8082
      #   env:
      #   - name: PORT
      #     value: "8082"