apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: wog
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  # The selector tells the service on which deployment it should be applied
  selector:
    app: wog