# Wishlist deployment yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wog-deployment
  labels:
    app: wog
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: wog   
  template:
    metadata:
      labels:
        app: wog
    spec:
      containers:
      - name: wog #1st container
        image: yahel777/wog-app:v1 #Dockerhub image
        ports:
        - containerPort: 5000 #Exposes the port  of the container
        env:
        - name: PORT #Env variable key passed to container that is read by app
          value: "5000" # Value of the env port.
        - name: DB_HOST
          value: db
      - name: api #2nd container
        image: yahel777/wog-api:v1
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: DB_HOST
          value: db
      # - name: auth #3rd container
      #   image: karthequian/wishlist-auth:1.0
      #   ports:
      #   - containerPort: 8082
      #   env:
      #   - name: PORT
      #     value: "8082"